### ISSUE TITLE
Not Escaping ">" In String Between Tags

### ISSUE THREAD

**Issue by ziplokk1** [michaelkourlas/node-xmlcreate#5]
See https://github.com/michaelkourlas/node-js2xmlparser/issues/74

**Comment by michaelkourlas** [comment]
In general, `>` doesn't need to be escaped. It's a valid character in XML text except when appearing in the form `]]>`.

From the [XML specification](https://www.w3.org/TR/xml/):

> The right angle bracket (>) may be represented using the string "`&gt;`", and must, for compatibility, be escaped using either "`&gt;`" or a character reference when it appears in the string "`]]>`" in content, when that string is not marking the end of a CDATA section.

**Comment by ziplokk1** [comment]
Got it. Thats what i thought. Unfortunately im dealing with an API that
requires it to be escaped. Would it be an issue with you if i forked and
hosted a clone to do that kind of escaping on NPM?

**Comment by michaelkourlas** [comment]
Sure -- it's open source.
